name=ArduClaw
version=0.1.0
author=Kartikeyan Srinivasan
maintainer=@KartikS417
sentence=AI Agent Framework for ESP32 with multi-channel support.
paragraph=Supports OpenAI, Sarvam AI, Telegram, Webhook, optional SD storage.
category=Communication
url=https://github.com/KartikS417/Arduclaw
architectures=esp32
license=MIT